services:
  redis:
    image: redis:latest
    ports:
      - 127.0.0.1:${REDIS_PORT:-6379}:6379
    networks:
      - filepizza
    volumes:
      - redis_data:/data
  coturn:
    image: coturn/coturn
    ports:
      - 3478:3478
      - 3478:3478/udp
      - 5349:5349
      - 5349:5349/udp
      - 60000-60128:60000-60128/udp
    environment:
      - DETECT_EXTERNAL_IP=yes
      - DETECT_RELAY_IP=yes
      - EXTERNAL_IP=${EXTERNAL_IP:-}
    command: -n --log-file=stdout --redis-userdb="ip=redis connect_timeout=30" --min-port=60000 --max-port=60128
    networks:
      - filepizza
  filepizza:
    build: .
    image: kern/filepizza:latest
    ports:
      - 127.0.0.1:8080:80
    environment:
      - PORT=80
      - REDIS_URL=redis://redis:${REDIS_PORT:-6379}
      - COTURN_ENABLED=true
      - TURN_REALM=https://${HOST_DOMAIN}
      - TURN_HOST=${HOST_DOMAIN}
      - API_ORIGINS=${API_ORIGINS}
      - CLOUDFLARE_TUNNEL=true
      - PEERJS_SERVERS=${PEERJS_SERVERS:-}
    networks:
      - filepizza
    depends_on:
      - redis
    env_file:
      - .env

networks:
  filepizza:
    driver: bridge

volumes:
  redis_data: